#!/bin/bash

set -e
set -u

if [[ ! -f $0 ]]; then
    echo "call on real install file!"
    exit 1
fi

install="$(dirname "$0")"

pushd "$install" > /dev/null

dotdir="$(basename "$(pwd -L)")"

install_links () {
    local src=${1}
    local tgt=${2}
    local back_to_home=${3}
    for t in $(find "$src" -mindepth 1 -maxdepth 1); do
        t="$(basename "$t")"
        case "$t" in
            .git) ;;
            .gitignore) ;;
            .gitmodules) ;;
            LICENSE) ;;
            README.md) ;;
            install) ;;
            *.NO_INSTALL)
                install_links "$src/$t" "$tgt/${t%.NO_INSTALL}" "$back_to_home/.."
                ;;
            *)
                cd "../$tgt" # back to home, into correspondig dir
                file="$(realpath -s --relative-to "$back_to_home" "$t")"
                target="$(realpath -s --relative-to . "$back_to_home/$dotdir/$src/$t")"
                if [[ -L $t && $(readlink "$t") == $target ]]; then
                    echo "          \"$file\""
                elif [[ -e $t ]]; then
                    echo "skipped   \"$file\""
                else
                    ln -s "$target" .
                    echo "installed \"$file\""
                fi
                cd "$back_to_home/$dotdir"
                ;;
        esac
    done
}

install_links . . .

popd > /dev/null
